//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rush2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimDamage
    {
        public int Id { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> DamageId { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual Damage Damage { get; set; }
    }
}
